

export const USER_OTP_LOGIN_REQUEST = "USER_OTP_LOGIN_REQUEST";
export const USER_OTP_LOGIN_SUCCESS = "USER_OTP_LOGIN_SUCCESS";
export const USER_OTP_LOGIN_FAILURE = "USER_OTP_LOGIN_FAILURE";

export const USER_LOGIN_PASS_REQUEST = "USER_LOGIN_PASS_REQUEST";
export const USER_LOGIN_PASS_SUCCESS = "USER_LOGIN_PASS_SUCCESS";
export const USER_LOGIN_PASS_FAILURE = "USER_LOGIN_PASS_FAILURE";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";