
// signup
export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

// login with password
export const USER_LOGIN_PASS_REQUEST = "USER_LOGIN_PASS_REQUEST";
export const USER_LOGIN_PASS_SUCCESS = "USER_LOGIN_PASS_SUCCESS";
export const USER_LOGIN_PASS_FAILURE = "USER_LOGIN_PASS_FAILURE";

// otplogin
export const USER_OTP_LOGIN_REQUEST = "USER_OTP_LOGIN_REQUEST";
export const USER_OTP_LOGIN_SUCCESS = "USER_OTP_LOGIN_SUCCESS";
export const USER_OTP_LOGIN_FAILURE = "USER_OTP_LOGIN_FAILURE";

// mobile save
export const USER_MOBILE_SAVE = "USER_MOBILE_SAVE";


// login otp verify
export const USER_OTP_VERIFY_FAILURE = "USER_OTP_VERIFY_FAILURE";
export const USER_OTP_VERIFY_SUCCESS = "USER_OTP_VERIFY_SUCCESS";
export const USER_OTP_VERIFY_REQUEST = "USER_OTP_VERIFY_REQUEST";

// google oauth login
export const USER_OAUTH_FAILURE = "USER_OAUTH_FAILURE";
export const USER_OAUTH_REQUEST = "USER_OAUTH_REQUEST";
export const USER_OAUTH_SUCCESS = "USER_OAUTH_SUCCESS";

// logout
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

// hotel listing
export const GET_HOTEL_LISTING_FAILURE = "GET_HOTEL_LISTING_FAILURE";
export const GET_HOTEL_LISTING_SUCCESS = "GET_HOTEL_LISTING_SUCCESS";
export const GET_HOTEL_LISTING_REQUEST = "GET_HOTEL_LISTING_REQUEST";
